version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: always
    container_name: pg-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
     - pg-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 

volumes:
  pg-db:
