definitions:
  areas.areaActivateRequest:
    properties:
      activated:
        type: boolean
      area_id:
        type: integer
    type: object
  areas.userArea:
    properties:
      action:
        $ref: '#/definitions/serviceinterface.ServiceStatus'
      activated:
        type: boolean
      id:
        type: integer
      reactions:
        items:
          $ref: '#/definitions/serviceinterface.ServiceStatus'
        type: array
    type: object
  controllers.AboutInfos:
    properties:
      client:
        $ref: '#/definitions/controllers.clientInfos'
      server:
        $ref: '#/definitions/controllers.serverInfos'
    type: object
  controllers.TokenCreateRequest:
    properties:
      provider:
        type: string
      token:
        type: string
      user_id:
        type: string
    type: object
  controllers.TokenInformations:
    properties:
      provider:
        type: string
      user_id:
        type: string
    type: object
  controllers.UserInformations:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      password:
        type: string
    type: object
  controllers.clientInfos:
    properties:
      host:
        type: string
    type: object
  controllers.credentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  controllers.microservice:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  controllers.serverInfos:
    properties:
      current_time:
        type: integer
      services:
        items:
          $ref: '#/definitions/controllers.serverService'
        type: array
    type: object
  controllers.serverService:
    properties:
      actions:
        items:
          $ref: '#/definitions/controllers.microservice'
        type: array
      name:
        type: string
      reactions:
        items:
          $ref: '#/definitions/controllers.microservice'
        type: array
    type: object
  controllers.userSignUp:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    type: object
  log_types.UserLogInfos:
    properties:
      token:
        type: string
      user_id:
        type: integer
    type: object
  models.Action:
    properties:
      ingredients:
        additionalProperties: {}
        type: object
      microservice:
        type: string
      service:
        type: string
    type: object
  models.AreaScenario:
    properties:
      action:
        $ref: '#/definitions/models.Action'
      reaction:
        $ref: '#/definitions/models.Reaction'
    type: object
  models.Reaction:
    properties:
      ingredients:
        additionalProperties: {}
        type: object
      microservice:
        type: string
      service:
        type: string
    type: object
  models.UpdatableUserData:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    type: object
  serviceinterface.ActionResponseStatus:
    properties:
      action_id:
        type: integer
      description:
        type: string
    type: object
  serviceinterface.IngredientDescriptor:
    properties:
      description:
        type: string
      required:
        type: boolean
      type:
        type: string
      value: {}
    type: object
  serviceinterface.Ingredients:
    additionalProperties:
      $ref: '#/definitions/serviceinterface.IngredientDescriptor'
    type: object
  serviceinterface.MicroserviceDescriptor:
    properties:
      ingredients:
        $ref: '#/definitions/serviceinterface.Ingredients'
      name:
        description: Name of the microservice
        type: string
      ref_name:
        description: Reference Name of the microservice as it is named in the server
        type: string
      type:
        description: Type of service action or reaction
        type: string
    type: object
  serviceinterface.ServiceStatus:
    properties:
      microservices:
        items:
          $ref: '#/definitions/serviceinterface.MicroserviceDescriptor'
        type: array
      name:
        description: Name of the service
        type: string
      ref_name:
        description: Reference Name of the service as it is named in the server
        type: string
    type: object
  serviceinterface.SetActivatedResponseStatus:
    properties:
      action_id:
        type: integer
      activated:
        type: boolean
      description:
        type: string
    type: object
info:
  contact: {}
  description: This is a the document of the Backend routes of the application AREA
  title: Swagger AREA API
  version: "1.0"
paths:
  /about.json:
    get:
      consumes:
      - application/json
      description: json giving the list of handled action-reaction services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.AboutInfos'
      summary: List of handled services
      tags:
      - About
  /area/activate:
    put:
      consumes:
      - application/json
      description: Activate/Deactivate user's area
      parameters:
      - description: Informations about the activation of an area
        in: body
        name: area
        required: true
        schema:
          $ref: '#/definitions/areas.areaActivateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serviceinterface.SetActivatedResponseStatus'
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Activate/Deactivate an area
      tags:
      - Area
  /area/create/{service}:
    post:
      consumes:
      - application/json
      description: Register a new Area in the application
      parameters:
      - description: Service Name
        in: path
        name: service
        required: true
        type: string
      - description: Full body of an Area Scenario
        in: body
        name: area
        required: true
        schema:
          $ref: '#/definitions/models.AreaScenario'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serviceinterface.ActionResponseStatus'
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Create a new Area
      tags:
      - Area
  /area/create/list:
    get:
      consumes:
      - application/json
      description: List all available areas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/serviceinterface.ServiceStatus'
            type: array
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: List available areas
      tags:
      - Area
  /area/list:
    get:
      consumes:
      - application/json
      description: List all user's area
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/areas.userArea'
            type: array
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: List User's area
      tags:
      - Area
  /login/:
    post:
      consumes:
      - application/json
      description: Login a user if he has the correct credentials and returns the
        tokens and the user_id
      parameters:
      - description: Credentials of the user who wants to connect
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/controllers.credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/log_types.UserLogInfos'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sign-In
      tags:
      - Account
  /oauth/:
    post:
      consumes:
      - application/json
      description: Create account with code from redirect url
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/log_types.UserLogInfos'
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create account with oauth
      tags:
      - Account
  /oauth/{service}:
    get:
      consumes:
      - application/json
      description: Get the oauth redirect url for a service
      parameters:
      - description: Redirect URL for the oauth
        in: query
        name: redirect_uri
        required: true
        type: string
      - description: Name of the service to use oauth with
        in: path
        name: service
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
      summary: Get an oauth url for a service
      tags:
      - Account
  /ping:
    get:
      description: Pong
      produces:
      - application/json
      responses:
        "200":
          description: pong
      security:
      - ApiKeyAuth: []
      summary: Prints pong
      tags:
      - Ping
  /sign-up/:
    post:
      consumes:
      - application/json
      description: register an account by giving credentials
      parameters:
      - description: New User informations to sign-up to the app
        in: body
        name: newUser
        required: true
        schema:
          $ref: '#/definitions/controllers.userSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.userSignUp'
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Sign-up a new account
      tags:
      - Account
  /token:
    delete:
      consumes:
      - application/json
      description: Delete a token from a user_id and a provider
      parameters:
      - description: Remote Service Name
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.TokenInformations'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Delete a token
      tags:
      - Token
    get:
      consumes:
      - application/json
      description: Get all the tokens of the current logged user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.TokenInformations'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get all the tokens from a user
      tags:
      - Token
    post:
      consumes:
      - application/json
      description: Create a token from a user_id and a provider
      parameters:
      - description: Token creation request informations
        in: body
        name: tokenCreateRequest
        required: true
        schema:
          $ref: '#/definitions/controllers.TokenCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.TokenInformations'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Create a token
      tags:
      - Token
  /token/{provider}:
    get:
      consumes:
      - application/json
      description: Get a the token associated to the remote provider of the user
      parameters:
      - description: Remote Service Name
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.TokenInformations'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get user's token
      tags:
      - Token
  /user/:
    post:
      consumes:
      - application/json
      description: Create a new user in database
      parameters:
      - description: User's information
        in: body
        name: userInfos
        required: true
        schema:
          $ref: '#/definitions/controllers.UserInformations'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserInformations'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Create a new user
      tags:
      - User
  /user/me:
    get:
      consumes:
      - application/json
      description: Get user's information based on his ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserInformations'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get User By ID
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update some informations about the user
      parameters:
      - description: Updatable user's informations
        in: body
        name: updatableDatas
        required: true
        schema:
          $ref: '#/definitions/models.UpdatableUserData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UpdatableUserData'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Update User datas
      tags:
      - User
  /webhook/{service}/{microservice}/{action_id}:
    post:
      consumes:
      - application/json
      description: Webhook Endpoint for the remote services payloads
      parameters:
      - description: Service Name
        in: path
        name: service
        required: true
        type: string
      - description: Microservice Name
        in: path
        name: microservice
        required: true
        type: string
      - description: Action ID for the reaction service
        in: path
        name: action_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema: {}
      summary: Webhook Endpoint
      tags:
      - Area
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
