import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '../styles/global.css'



const avenirNext = localFont({
    src: [
        {
            path: '../public/fonts/AvenirNextLTPro-Regular.otf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../public/fonts/AvenirNextLTPro-Bold.otf',
            weight: '700',
            style: 'normal',
        },
        // Add more variations if needed
    ],
    variable: '--font-avenir-next',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html className="scroll-smooth" lang="en">
          <body
            className={`${avenirNext.variable} antialiased bg-slate-800`}
          >
            {children}
          </body>
        </html>
  );
}
