// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.6
// source: gRPC/proto/dateTimeService.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activated bool  `protobuf:"varint,1,opt,name=activated,proto3" json:"activated,omitempty"`
	ActionId  int32 `protobuf:"varint,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Minutes   int32 `protobuf:"varint,3,opt,name=minutes,proto3" json:"minutes,omitempty"`
	Hours     int32 `protobuf:"varint,4,opt,name=hours,proto3" json:"hours,omitempty"`
	DayMonth  int64 `protobuf:"varint,5,opt,name=day_month,json=dayMonth,proto3" json:"day_month,omitempty"`
	Month     int64 `protobuf:"varint,6,opt,name=month,proto3" json:"month,omitempty"`
	DayWeek   int64 `protobuf:"varint,7,opt,name=day_week,json=dayWeek,proto3" json:"day_week,omitempty"`
}

func (x *TriggerTimeRequest) Reset() {
	*x = TriggerTimeRequest{}
	mi := &file_gRPC_proto_dateTimeService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTimeRequest) ProtoMessage() {}

func (x *TriggerTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_dateTimeService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTimeRequest.ProtoReflect.Descriptor instead.
func (*TriggerTimeRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_dateTimeService_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerTimeRequest) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *TriggerTimeRequest) GetActionId() int32 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *TriggerTimeRequest) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

func (x *TriggerTimeRequest) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *TriggerTimeRequest) GetDayMonth() int64 {
	if x != nil {
		return x.DayMonth
	}
	return 0
}

func (x *TriggerTimeRequest) GetMonth() int64 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *TriggerTimeRequest) GetDayWeek() int64 {
	if x != nil {
		return x.DayWeek
	}
	return 0
}

type TriggerTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TriggerTimeResponse) Reset() {
	*x = TriggerTimeResponse{}
	mi := &file_gRPC_proto_dateTimeService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTimeResponse) ProtoMessage() {}

func (x *TriggerTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_dateTimeService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTimeResponse.ProtoReflect.Descriptor instead.
func (*TriggerTimeResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_dateTimeService_proto_rawDescGZIP(), []int{1}
}

var File_gRPC_proto_dateTimeService_proto protoreflect.FileDescriptor

var file_gRPC_proto_dateTimeService_proto_rawDesc = []byte{
	0x0a, 0x20, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xcd, 0x01, 0x0a,
	0x12, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x75, 0x72,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x61, 0x79, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x61, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x6e, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74,
	0x68, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x61, 0x79, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x61, 0x79, 0x57, 0x65, 0x65, 0x6b, 0x22, 0x15, 0x0a, 0x13,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x61, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x43, 0x72, 0x6f, 0x6e, 0x4a, 0x6f, 0x62, 0x12, 0x1c, 0x2e, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67,
	0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gRPC_proto_dateTimeService_proto_rawDescOnce sync.Once
	file_gRPC_proto_dateTimeService_proto_rawDescData = file_gRPC_proto_dateTimeService_proto_rawDesc
)

func file_gRPC_proto_dateTimeService_proto_rawDescGZIP() []byte {
	file_gRPC_proto_dateTimeService_proto_rawDescOnce.Do(func() {
		file_gRPC_proto_dateTimeService_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPC_proto_dateTimeService_proto_rawDescData)
	})
	return file_gRPC_proto_dateTimeService_proto_rawDescData
}

var file_gRPC_proto_dateTimeService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gRPC_proto_dateTimeService_proto_goTypes = []any{
	(*TriggerTimeRequest)(nil),  // 0: dateTime.TriggerTimeRequest
	(*TriggerTimeResponse)(nil), // 1: dateTime.TriggerTimeResponse
}
var file_gRPC_proto_dateTimeService_proto_depIdxs = []int32{
	0, // 0: dateTime.DateTimeService.LaunchCronJob:input_type -> dateTime.TriggerTimeRequest
	1, // 1: dateTime.DateTimeService.LaunchCronJob:output_type -> dateTime.TriggerTimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gRPC_proto_dateTimeService_proto_init() }
func file_gRPC_proto_dateTimeService_proto_init() {
	if File_gRPC_proto_dateTimeService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPC_proto_dateTimeService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_proto_dateTimeService_proto_goTypes,
		DependencyIndexes: file_gRPC_proto_dateTimeService_proto_depIdxs,
		MessageInfos:      file_gRPC_proto_dateTimeService_proto_msgTypes,
	}.Build()
	File_gRPC_proto_dateTimeService_proto = out.File
	file_gRPC_proto_dateTimeService_proto_rawDesc = nil
	file_gRPC_proto_dateTimeService_proto_goTypes = nil
	file_gRPC_proto_dateTimeService_proto_depIdxs = nil
}
