// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: gRPC/proto/dateTimeService.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DateTimeService_LaunchCronJob_FullMethodName = "/dateTime.DateTimeService/LaunchCronJob"
)

// DateTimeServiceClient is the client API for DateTimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DateTimeServiceClient interface {
	LaunchCronJob(ctx context.Context, in *TriggerTimeRequest, opts ...grpc.CallOption) (*TriggerTimeResponse, error)
}

type dateTimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDateTimeServiceClient(cc grpc.ClientConnInterface) DateTimeServiceClient {
	return &dateTimeServiceClient{cc}
}

func (c *dateTimeServiceClient) LaunchCronJob(ctx context.Context, in *TriggerTimeRequest, opts ...grpc.CallOption) (*TriggerTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerTimeResponse)
	err := c.cc.Invoke(ctx, DateTimeService_LaunchCronJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DateTimeServiceServer is the server API for DateTimeService service.
// All implementations must embed UnimplementedDateTimeServiceServer
// for forward compatibility.
type DateTimeServiceServer interface {
	LaunchCronJob(context.Context, *TriggerTimeRequest) (*TriggerTimeResponse, error)
	mustEmbedUnimplementedDateTimeServiceServer()
}

// UnimplementedDateTimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDateTimeServiceServer struct{}

func (UnimplementedDateTimeServiceServer) LaunchCronJob(context.Context, *TriggerTimeRequest) (*TriggerTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchCronJob not implemented")
}
func (UnimplementedDateTimeServiceServer) mustEmbedUnimplementedDateTimeServiceServer() {}
func (UnimplementedDateTimeServiceServer) testEmbeddedByValue()                         {}

// UnsafeDateTimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DateTimeServiceServer will
// result in compilation errors.
type UnsafeDateTimeServiceServer interface {
	mustEmbedUnimplementedDateTimeServiceServer()
}

func RegisterDateTimeServiceServer(s grpc.ServiceRegistrar, srv DateTimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDateTimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DateTimeService_ServiceDesc, srv)
}

func _DateTimeService_LaunchCronJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DateTimeServiceServer).LaunchCronJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DateTimeService_LaunchCronJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DateTimeServiceServer).LaunchCronJob(ctx, req.(*TriggerTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DateTimeService_ServiceDesc is the grpc.ServiceDesc for DateTimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DateTimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dateTime.DateTimeService",
	HandlerType: (*DateTimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LaunchCronJob",
			Handler:    _DateTimeService_LaunchCronJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/proto/dateTimeService.proto",
}
