// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.6
// source: gRPC/proto/github_service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRepoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner       string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo        string `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"` // There is more to add
}

func (x *UpdateRepoReq) Reset() {
	*x = UpdateRepoReq{}
	mi := &file_gRPC_proto_github_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoReq) ProtoMessage() {}

func (x *UpdateRepoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_github_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoReq.ProtoReflect.Descriptor instead.
func (*UpdateRepoReq) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_github_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRepoReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *UpdateRepoReq) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *UpdateRepoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRepoReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateRepoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp string `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"` // Update to a more specific response
}

func (x *UpdateRepoRes) Reset() {
	*x = UpdateRepoRes{}
	mi := &file_gRPC_proto_github_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoRes) ProtoMessage() {}

func (x *UpdateRepoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_github_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoRes.ProtoReflect.Descriptor instead.
func (*UpdateRepoRes) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_github_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRepoRes) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

var File_gRPC_proto_github_service_proto protoreflect.FileDescriptor

var file_gRPC_proto_github_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x22, 0x6f, 0x0a, 0x0d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x65, 0x70, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x32,
	0x53, 0x0a, 0x0d, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x42, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x15, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x52,
	0x65, 0x71, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gRPC_proto_github_service_proto_rawDescOnce sync.Once
	file_gRPC_proto_github_service_proto_rawDescData = file_gRPC_proto_github_service_proto_rawDesc
)

func file_gRPC_proto_github_service_proto_rawDescGZIP() []byte {
	file_gRPC_proto_github_service_proto_rawDescOnce.Do(func() {
		file_gRPC_proto_github_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPC_proto_github_service_proto_rawDescData)
	})
	return file_gRPC_proto_github_service_proto_rawDescData
}

var file_gRPC_proto_github_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gRPC_proto_github_service_proto_goTypes = []any{
	(*UpdateRepoReq)(nil), // 0: github.UpdateRepoReq
	(*UpdateRepoRes)(nil), // 1: github.UpdateRepoRes
}
var file_gRPC_proto_github_service_proto_depIdxs = []int32{
	0, // 0: github.GithubService.UpdateRepository:input_type -> github.UpdateRepoReq
	0, // 1: github.GithubService.UpdateRepository:output_type -> github.UpdateRepoReq
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gRPC_proto_github_service_proto_init() }
func file_gRPC_proto_github_service_proto_init() {
	if File_gRPC_proto_github_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPC_proto_github_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_proto_github_service_proto_goTypes,
		DependencyIndexes: file_gRPC_proto_github_service_proto_depIdxs,
		MessageInfos:      file_gRPC_proto_github_service_proto_msgTypes,
	}.Build()
	File_gRPC_proto_github_service_proto = out.File
	file_gRPC_proto_github_service_proto_rawDesc = nil
	file_gRPC_proto_github_service_proto_goTypes = nil
	file_gRPC_proto_github_service_proto_depIdxs = nil
}
