// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: gRPC/proto/gitlab_service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitlabService_CreateFile_FullMethodName     = "/gitlab.GitlabService/CreateFile"
	GitlabService_UpdateFile_FullMethodName     = "/gitlab.GitlabService/UpdateFile"
	GitlabService_DeleteFile_FullMethodName     = "/gitlab.GitlabService/DeleteFile"
	GitlabService_MarkItemAsDone_FullMethodName = "/gitlab.GitlabService/MarkItemAsDone"
)

// GitlabServiceClient is the client API for GitlabService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitlabServiceClient interface {
	CreateFile(ctx context.Context, in *CreateLabRepoFile, opts ...grpc.CallOption) (*CreateLabRepoFile, error)
	UpdateFile(ctx context.Context, in *UpdateLabRepoFile, opts ...grpc.CallOption) (*UpdateLabRepoFile, error)
	DeleteFile(ctx context.Context, in *DeleteLabRepoFile, opts ...grpc.CallOption) (*DeleteLabRepoFile, error)
	MarkItemAsDone(ctx context.Context, in *TodoLabItemDone, opts ...grpc.CallOption) (*TodoLabItemDone, error)
}

type gitlabServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGitlabServiceClient(cc grpc.ClientConnInterface) GitlabServiceClient {
	return &gitlabServiceClient{cc}
}

func (c *gitlabServiceClient) CreateFile(ctx context.Context, in *CreateLabRepoFile, opts ...grpc.CallOption) (*CreateLabRepoFile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLabRepoFile)
	err := c.cc.Invoke(ctx, GitlabService_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitlabServiceClient) UpdateFile(ctx context.Context, in *UpdateLabRepoFile, opts ...grpc.CallOption) (*UpdateLabRepoFile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLabRepoFile)
	err := c.cc.Invoke(ctx, GitlabService_UpdateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitlabServiceClient) DeleteFile(ctx context.Context, in *DeleteLabRepoFile, opts ...grpc.CallOption) (*DeleteLabRepoFile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLabRepoFile)
	err := c.cc.Invoke(ctx, GitlabService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitlabServiceClient) MarkItemAsDone(ctx context.Context, in *TodoLabItemDone, opts ...grpc.CallOption) (*TodoLabItemDone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TodoLabItemDone)
	err := c.cc.Invoke(ctx, GitlabService_MarkItemAsDone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitlabServiceServer is the server API for GitlabService service.
// All implementations must embed UnimplementedGitlabServiceServer
// for forward compatibility.
type GitlabServiceServer interface {
	CreateFile(context.Context, *CreateLabRepoFile) (*CreateLabRepoFile, error)
	UpdateFile(context.Context, *UpdateLabRepoFile) (*UpdateLabRepoFile, error)
	DeleteFile(context.Context, *DeleteLabRepoFile) (*DeleteLabRepoFile, error)
	MarkItemAsDone(context.Context, *TodoLabItemDone) (*TodoLabItemDone, error)
	mustEmbedUnimplementedGitlabServiceServer()
}

// UnimplementedGitlabServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitlabServiceServer struct{}

func (UnimplementedGitlabServiceServer) CreateFile(context.Context, *CreateLabRepoFile) (*CreateLabRepoFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedGitlabServiceServer) UpdateFile(context.Context, *UpdateLabRepoFile) (*UpdateLabRepoFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFile not implemented")
}
func (UnimplementedGitlabServiceServer) DeleteFile(context.Context, *DeleteLabRepoFile) (*DeleteLabRepoFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedGitlabServiceServer) MarkItemAsDone(context.Context, *TodoLabItemDone) (*TodoLabItemDone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkItemAsDone not implemented")
}
func (UnimplementedGitlabServiceServer) mustEmbedUnimplementedGitlabServiceServer() {}
func (UnimplementedGitlabServiceServer) testEmbeddedByValue()                       {}

// UnsafeGitlabServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitlabServiceServer will
// result in compilation errors.
type UnsafeGitlabServiceServer interface {
	mustEmbedUnimplementedGitlabServiceServer()
}

func RegisterGitlabServiceServer(s grpc.ServiceRegistrar, srv GitlabServiceServer) {
	// If the following call pancis, it indicates UnimplementedGitlabServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitlabService_ServiceDesc, srv)
}

func _GitlabService_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLabRepoFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitlabServiceServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitlabService_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitlabServiceServer).CreateFile(ctx, req.(*CreateLabRepoFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitlabService_UpdateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLabRepoFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitlabServiceServer).UpdateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitlabService_UpdateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitlabServiceServer).UpdateFile(ctx, req.(*UpdateLabRepoFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitlabService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLabRepoFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitlabServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitlabService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitlabServiceServer).DeleteFile(ctx, req.(*DeleteLabRepoFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitlabService_MarkItemAsDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoLabItemDone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitlabServiceServer).MarkItemAsDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitlabService_MarkItemAsDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitlabServiceServer).MarkItemAsDone(ctx, req.(*TodoLabItemDone))
	}
	return interceptor(ctx, in, info, handler)
}

// GitlabService_ServiceDesc is the grpc.ServiceDesc for GitlabService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitlabService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitlab.GitlabService",
	HandlerType: (*GitlabServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFile",
			Handler:    _GitlabService_CreateFile_Handler,
		},
		{
			MethodName: "UpdateFile",
			Handler:    _GitlabService_UpdateFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _GitlabService_DeleteFile_Handler,
		},
		{
			MethodName: "MarkItemAsDone",
			Handler:    _GitlabService_MarkItemAsDone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/proto/gitlab_service.proto",
}
