// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.6
// source: gRPC/proto/reactionService.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReactionRequest) Reset() {
	*x = ReactionRequest{}
	mi := &file_gRPC_proto_reactionService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionRequest) ProtoMessage() {}

func (x *ReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_reactionService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionRequest.ProtoReflect.Descriptor instead.
func (*ReactionRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_reactionService_proto_rawDescGZIP(), []int{0}
}

type ReactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReactionResponse) Reset() {
	*x = ReactionResponse{}
	mi := &file_gRPC_proto_reactionService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionResponse) ProtoMessage() {}

func (x *ReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_reactionService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionResponse.ProtoReflect.Descriptor instead.
func (*ReactionResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_reactionService_proto_rawDescGZIP(), []int{1}
}

var File_gRPC_proto_reactionService_proto protoreflect.FileDescriptor

var file_gRPC_proto_reactionService_proto_rawDesc = []byte{
	0x0a, 0x20, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x11, 0x0a, 0x0f,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x12, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x5c, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0e, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x72, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x72, 0x65, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gRPC_proto_reactionService_proto_rawDescOnce sync.Once
	file_gRPC_proto_reactionService_proto_rawDescData = file_gRPC_proto_reactionService_proto_rawDesc
)

func file_gRPC_proto_reactionService_proto_rawDescGZIP() []byte {
	file_gRPC_proto_reactionService_proto_rawDescOnce.Do(func() {
		file_gRPC_proto_reactionService_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPC_proto_reactionService_proto_rawDescData)
	})
	return file_gRPC_proto_reactionService_proto_rawDescData
}

var file_gRPC_proto_reactionService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gRPC_proto_reactionService_proto_goTypes = []any{
	(*ReactionRequest)(nil),  // 0: reaction.ReactionRequest
	(*ReactionResponse)(nil), // 1: reaction.ReactionResponse
}
var file_gRPC_proto_reactionService_proto_depIdxs = []int32{
	0, // 0: reaction.ReactionService.LaunchReaction:input_type -> reaction.ReactionRequest
	1, // 1: reaction.ReactionService.LaunchReaction:output_type -> reaction.ReactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gRPC_proto_reactionService_proto_init() }
func file_gRPC_proto_reactionService_proto_init() {
	if File_gRPC_proto_reactionService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPC_proto_reactionService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_proto_reactionService_proto_goTypes,
		DependencyIndexes: file_gRPC_proto_reactionService_proto_depIdxs,
		MessageInfos:      file_gRPC_proto_reactionService_proto_msgTypes,
	}.Build()
	File_gRPC_proto_reactionService_proto = out.File
	file_gRPC_proto_reactionService_proto_rawDesc = nil
	file_gRPC_proto_reactionService_proto_goTypes = nil
	file_gRPC_proto_reactionService_proto_depIdxs = nil
}
