// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: gRPC/proto/spotify_service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpotifyStopInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpotifyStopInfo) Reset() {
	*x = SpotifyStopInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_proto_spotify_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotifyStopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotifyStopInfo) ProtoMessage() {}

func (x *SpotifyStopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_spotify_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotifyStopInfo.ProtoReflect.Descriptor instead.
func (*SpotifyStopInfo) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_spotify_service_proto_rawDescGZIP(), []int{0}
}

type SpotifyCreatePlaylist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistName        string `protobuf:"bytes,1,opt,name=playlistName,proto3" json:"playlistName,omitempty"`
	PlaylistDescription string `protobuf:"bytes,2,opt,name=playlistDescription,proto3" json:"playlistDescription,omitempty"`
	Public              string `protobuf:"bytes,3,opt,name=public,proto3" json:"public,omitempty"`
}

func (x *SpotifyCreatePlaylist) Reset() {
	*x = SpotifyCreatePlaylist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_proto_spotify_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotifyCreatePlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotifyCreatePlaylist) ProtoMessage() {}

func (x *SpotifyCreatePlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_spotify_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotifyCreatePlaylist.ProtoReflect.Descriptor instead.
func (*SpotifyCreatePlaylist) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_spotify_service_proto_rawDescGZIP(), []int{1}
}

func (x *SpotifyCreatePlaylist) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

func (x *SpotifyCreatePlaylist) GetPlaylistDescription() string {
	if x != nil {
		return x.PlaylistDescription
	}
	return ""
}

func (x *SpotifyCreatePlaylist) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

var File_gRPC_proto_spotify_service_proto protoreflect.FileDescriptor

var file_gRPC_proto_spotify_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x53,
	0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x85,
	0x01, 0x0a, 0x15, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x13,
	0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70, 0x6c, 0x61, 0x79, 0x6c,
	0x69, 0x73, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x32, 0xa6, 0x01, 0x0a, 0x0e, 0x53, 0x70, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x08, 0x53, 0x74, 0x6f,
	0x70, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x18, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x53, 0x74, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e,
	0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42,
	0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72,
	0x65, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gRPC_proto_spotify_service_proto_rawDescOnce sync.Once
	file_gRPC_proto_spotify_service_proto_rawDescData = file_gRPC_proto_spotify_service_proto_rawDesc
)

func file_gRPC_proto_spotify_service_proto_rawDescGZIP() []byte {
	file_gRPC_proto_spotify_service_proto_rawDescOnce.Do(func() {
		file_gRPC_proto_spotify_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPC_proto_spotify_service_proto_rawDescData)
	})
	return file_gRPC_proto_spotify_service_proto_rawDescData
}

var file_gRPC_proto_spotify_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gRPC_proto_spotify_service_proto_goTypes = []interface{}{
	(*SpotifyStopInfo)(nil),       // 0: spotify.SpotifyStopInfo
	(*SpotifyCreatePlaylist)(nil), // 1: spotify.SpotifyCreatePlaylist
}
var file_gRPC_proto_spotify_service_proto_depIdxs = []int32{
	0, // 0: spotify.SpotifyService.StopSong:input_type -> spotify.SpotifyStopInfo
	1, // 1: spotify.SpotifyService.CreatePlaylist:input_type -> spotify.SpotifyCreatePlaylist
	0, // 2: spotify.SpotifyService.StopSong:output_type -> spotify.SpotifyStopInfo
	1, // 3: spotify.SpotifyService.CreatePlaylist:output_type -> spotify.SpotifyCreatePlaylist
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gRPC_proto_spotify_service_proto_init() }
func file_gRPC_proto_spotify_service_proto_init() {
	if File_gRPC_proto_spotify_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gRPC_proto_spotify_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotifyStopInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_proto_spotify_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotifyCreatePlaylist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPC_proto_spotify_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_proto_spotify_service_proto_goTypes,
		DependencyIndexes: file_gRPC_proto_spotify_service_proto_depIdxs,
		MessageInfos:      file_gRPC_proto_spotify_service_proto_msgTypes,
	}.Build()
	File_gRPC_proto_spotify_service_proto = out.File
	file_gRPC_proto_spotify_service_proto_rawDesc = nil
	file_gRPC_proto_spotify_service_proto_goTypes = nil
	file_gRPC_proto_spotify_service_proto_depIdxs = nil
}
