// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: gRPC/proto/spotify_service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpotifyService_StopSong_FullMethodName          = "/spotify.SpotifyService/StopSong"
	SpotifyService_CreatePlaylist_FullMethodName    = "/spotify.SpotifyService/CreatePlaylist"
	SpotifyService_NextSong_FullMethodName          = "/spotify.SpotifyService/NextSong"
	SpotifyService_PreviousSong_FullMethodName      = "/spotify.SpotifyService/PreviousSong"
	SpotifyService_SetPlaybackVolume_FullMethodName = "/spotify.SpotifyService/SetPlaybackVolume"
	SpotifyService_LaunchSong_FullMethodName        = "/spotify.SpotifyService/LaunchSong"
	SpotifyService_AddSongToPlaylist_FullMethodName = "/spotify.SpotifyService/AddSongToPlaylist"
)

// SpotifyServiceClient is the client API for SpotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpotifyServiceClient interface {
	StopSong(ctx context.Context, in *SpotifyStopInfo, opts ...grpc.CallOption) (*SpotifyStopInfo, error)
	CreatePlaylist(ctx context.Context, in *SpotifyCreatePlaylist, opts ...grpc.CallOption) (*SpotifyCreatePlaylist, error)
	NextSong(ctx context.Context, in *SpotifyNextInfo, opts ...grpc.CallOption) (*SpotifyNextInfo, error)
	PreviousSong(ctx context.Context, in *SpotifyPreviousInfo, opts ...grpc.CallOption) (*SpotifyPreviousInfo, error)
	SetPlaybackVolume(ctx context.Context, in *SpotifySetPlaybackVolumeInfo, opts ...grpc.CallOption) (*SpotifySetPlaybackVolumeInfo, error)
	LaunchSong(ctx context.Context, in *SpotifyLauchSongInfo, opts ...grpc.CallOption) (*SpotifyLauchSongInfo, error)
	AddSongToPlaylist(ctx context.Context, in *SpotifyAddSongToPlaylist, opts ...grpc.CallOption) (*SpotifyAddSongToPlaylist, error)
}

type spotifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpotifyServiceClient(cc grpc.ClientConnInterface) SpotifyServiceClient {
	return &spotifyServiceClient{cc}
}

func (c *spotifyServiceClient) StopSong(ctx context.Context, in *SpotifyStopInfo, opts ...grpc.CallOption) (*SpotifyStopInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotifyStopInfo)
	err := c.cc.Invoke(ctx, SpotifyService_StopSong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyServiceClient) CreatePlaylist(ctx context.Context, in *SpotifyCreatePlaylist, opts ...grpc.CallOption) (*SpotifyCreatePlaylist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotifyCreatePlaylist)
	err := c.cc.Invoke(ctx, SpotifyService_CreatePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyServiceClient) NextSong(ctx context.Context, in *SpotifyNextInfo, opts ...grpc.CallOption) (*SpotifyNextInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotifyNextInfo)
	err := c.cc.Invoke(ctx, SpotifyService_NextSong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyServiceClient) PreviousSong(ctx context.Context, in *SpotifyPreviousInfo, opts ...grpc.CallOption) (*SpotifyPreviousInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotifyPreviousInfo)
	err := c.cc.Invoke(ctx, SpotifyService_PreviousSong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyServiceClient) SetPlaybackVolume(ctx context.Context, in *SpotifySetPlaybackVolumeInfo, opts ...grpc.CallOption) (*SpotifySetPlaybackVolumeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotifySetPlaybackVolumeInfo)
	err := c.cc.Invoke(ctx, SpotifyService_SetPlaybackVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyServiceClient) LaunchSong(ctx context.Context, in *SpotifyLauchSongInfo, opts ...grpc.CallOption) (*SpotifyLauchSongInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotifyLauchSongInfo)
	err := c.cc.Invoke(ctx, SpotifyService_LaunchSong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyServiceClient) AddSongToPlaylist(ctx context.Context, in *SpotifyAddSongToPlaylist, opts ...grpc.CallOption) (*SpotifyAddSongToPlaylist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotifyAddSongToPlaylist)
	err := c.cc.Invoke(ctx, SpotifyService_AddSongToPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpotifyServiceServer is the server API for SpotifyService service.
// All implementations must embed UnimplementedSpotifyServiceServer
// for forward compatibility.
type SpotifyServiceServer interface {
	StopSong(context.Context, *SpotifyStopInfo) (*SpotifyStopInfo, error)
	CreatePlaylist(context.Context, *SpotifyCreatePlaylist) (*SpotifyCreatePlaylist, error)
	NextSong(context.Context, *SpotifyNextInfo) (*SpotifyNextInfo, error)
	PreviousSong(context.Context, *SpotifyPreviousInfo) (*SpotifyPreviousInfo, error)
	SetPlaybackVolume(context.Context, *SpotifySetPlaybackVolumeInfo) (*SpotifySetPlaybackVolumeInfo, error)
	LaunchSong(context.Context, *SpotifyLauchSongInfo) (*SpotifyLauchSongInfo, error)
	AddSongToPlaylist(context.Context, *SpotifyAddSongToPlaylist) (*SpotifyAddSongToPlaylist, error)
	mustEmbedUnimplementedSpotifyServiceServer()
}

// UnimplementedSpotifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpotifyServiceServer struct{}

func (UnimplementedSpotifyServiceServer) StopSong(context.Context, *SpotifyStopInfo) (*SpotifyStopInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSong not implemented")
}
func (UnimplementedSpotifyServiceServer) CreatePlaylist(context.Context, *SpotifyCreatePlaylist) (*SpotifyCreatePlaylist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlaylist not implemented")
}
func (UnimplementedSpotifyServiceServer) NextSong(context.Context, *SpotifyNextInfo) (*SpotifyNextInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextSong not implemented")
}
func (UnimplementedSpotifyServiceServer) PreviousSong(context.Context, *SpotifyPreviousInfo) (*SpotifyPreviousInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviousSong not implemented")
}
func (UnimplementedSpotifyServiceServer) SetPlaybackVolume(context.Context, *SpotifySetPlaybackVolumeInfo) (*SpotifySetPlaybackVolumeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPlaybackVolume not implemented")
}
func (UnimplementedSpotifyServiceServer) LaunchSong(context.Context, *SpotifyLauchSongInfo) (*SpotifyLauchSongInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchSong not implemented")
}
func (UnimplementedSpotifyServiceServer) AddSongToPlaylist(context.Context, *SpotifyAddSongToPlaylist) (*SpotifyAddSongToPlaylist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSongToPlaylist not implemented")
}
func (UnimplementedSpotifyServiceServer) mustEmbedUnimplementedSpotifyServiceServer() {}
func (UnimplementedSpotifyServiceServer) testEmbeddedByValue()                        {}

// UnsafeSpotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpotifyServiceServer will
// result in compilation errors.
type UnsafeSpotifyServiceServer interface {
	mustEmbedUnimplementedSpotifyServiceServer()
}

func RegisterSpotifyServiceServer(s grpc.ServiceRegistrar, srv SpotifyServiceServer) {
	// If the following call pancis, it indicates UnimplementedSpotifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpotifyService_ServiceDesc, srv)
}

func _SpotifyService_StopSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotifyStopInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifyServiceServer).StopSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotifyService_StopSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifyServiceServer).StopSong(ctx, req.(*SpotifyStopInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotifyService_CreatePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotifyCreatePlaylist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifyServiceServer).CreatePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotifyService_CreatePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifyServiceServer).CreatePlaylist(ctx, req.(*SpotifyCreatePlaylist))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotifyService_NextSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotifyNextInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifyServiceServer).NextSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotifyService_NextSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifyServiceServer).NextSong(ctx, req.(*SpotifyNextInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotifyService_PreviousSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotifyPreviousInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifyServiceServer).PreviousSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotifyService_PreviousSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifyServiceServer).PreviousSong(ctx, req.(*SpotifyPreviousInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotifyService_SetPlaybackVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotifySetPlaybackVolumeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifyServiceServer).SetPlaybackVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotifyService_SetPlaybackVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifyServiceServer).SetPlaybackVolume(ctx, req.(*SpotifySetPlaybackVolumeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotifyService_LaunchSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotifyLauchSongInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifyServiceServer).LaunchSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotifyService_LaunchSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifyServiceServer).LaunchSong(ctx, req.(*SpotifyLauchSongInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotifyService_AddSongToPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotifyAddSongToPlaylist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifyServiceServer).AddSongToPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotifyService_AddSongToPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifyServiceServer).AddSongToPlaylist(ctx, req.(*SpotifyAddSongToPlaylist))
	}
	return interceptor(ctx, in, info, handler)
}

// SpotifyService_ServiceDesc is the grpc.ServiceDesc for SpotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spotify.SpotifyService",
	HandlerType: (*SpotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StopSong",
			Handler:    _SpotifyService_StopSong_Handler,
		},
		{
			MethodName: "CreatePlaylist",
			Handler:    _SpotifyService_CreatePlaylist_Handler,
		},
		{
			MethodName: "NextSong",
			Handler:    _SpotifyService_NextSong_Handler,
		},
		{
			MethodName: "PreviousSong",
			Handler:    _SpotifyService_PreviousSong_Handler,
		},
		{
			MethodName: "SetPlaybackVolume",
			Handler:    _SpotifyService_SetPlaybackVolume_Handler,
		},
		{
			MethodName: "LaunchSong",
			Handler:    _SpotifyService_LaunchSong_Handler,
		},
		{
			MethodName: "AddSongToPlaylist",
			Handler:    _SpotifyService_AddSongToPlaylist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/proto/spotify_service.proto",
}
