// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: gRPC/proto/weather_service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeatherService_NewTemperatureTrigger_FullMethodName = "/gitlab.WeatherService/NewTemperatureTrigger"
	WeatherService_NewIsDayTrigger_FullMethodName       = "/gitlab.WeatherService/NewIsDayTrigger"
)

// WeatherServiceClient is the client API for WeatherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherServiceClient interface {
	// Each hour, when temperature exceed a certain amount, do this
	NewTemperatureTrigger(ctx context.Context, in *TempTriggerReq, opts ...grpc.CallOption) (*TempTriggerReq, error)
	// Each Hour, when it is night, do this
	NewIsDayTrigger(ctx context.Context, in *IsDayTriggerReq, opts ...grpc.CallOption) (*IsDayTriggerReq, error)
}

type weatherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherServiceClient(cc grpc.ClientConnInterface) WeatherServiceClient {
	return &weatherServiceClient{cc}
}

func (c *weatherServiceClient) NewTemperatureTrigger(ctx context.Context, in *TempTriggerReq, opts ...grpc.CallOption) (*TempTriggerReq, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TempTriggerReq)
	err := c.cc.Invoke(ctx, WeatherService_NewTemperatureTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherServiceClient) NewIsDayTrigger(ctx context.Context, in *IsDayTriggerReq, opts ...grpc.CallOption) (*IsDayTriggerReq, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsDayTriggerReq)
	err := c.cc.Invoke(ctx, WeatherService_NewIsDayTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherServiceServer is the server API for WeatherService service.
// All implementations must embed UnimplementedWeatherServiceServer
// for forward compatibility.
type WeatherServiceServer interface {
	// Each hour, when temperature exceed a certain amount, do this
	NewTemperatureTrigger(context.Context, *TempTriggerReq) (*TempTriggerReq, error)
	// Each Hour, when it is night, do this
	NewIsDayTrigger(context.Context, *IsDayTriggerReq) (*IsDayTriggerReq, error)
	mustEmbedUnimplementedWeatherServiceServer()
}

// UnimplementedWeatherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeatherServiceServer struct{}

func (UnimplementedWeatherServiceServer) NewTemperatureTrigger(context.Context, *TempTriggerReq) (*TempTriggerReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTemperatureTrigger not implemented")
}
func (UnimplementedWeatherServiceServer) NewIsDayTrigger(context.Context, *IsDayTriggerReq) (*IsDayTriggerReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewIsDayTrigger not implemented")
}
func (UnimplementedWeatherServiceServer) mustEmbedUnimplementedWeatherServiceServer() {}
func (UnimplementedWeatherServiceServer) testEmbeddedByValue()                        {}

// UnsafeWeatherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherServiceServer will
// result in compilation errors.
type UnsafeWeatherServiceServer interface {
	mustEmbedUnimplementedWeatherServiceServer()
}

func RegisterWeatherServiceServer(s grpc.ServiceRegistrar, srv WeatherServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeatherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeatherService_ServiceDesc, srv)
}

func _WeatherService_NewTemperatureTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TempTriggerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).NewTemperatureTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherService_NewTemperatureTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).NewTemperatureTrigger(ctx, req.(*TempTriggerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherService_NewIsDayTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsDayTriggerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).NewIsDayTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherService_NewIsDayTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).NewIsDayTrigger(ctx, req.(*IsDayTriggerReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherService_ServiceDesc is the grpc.ServiceDesc for WeatherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitlab.WeatherService",
	HandlerType: (*WeatherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTemperatureTrigger",
			Handler:    _WeatherService_NewTemperatureTrigger_Handler,
		},
		{
			MethodName: "NewIsDayTrigger",
			Handler:    _WeatherService_NewIsDayTrigger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/proto/weather_service.proto",
}
