name: Push to mirror
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
env:
  MIRROR_URL: ${{ secrets.REPO_EPITECH_MIRROR }}
  GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}

jobs:
  check-web-compilation:
    if: "!contains(github.event.head_commit.message, '[skip CI]')"
    name: Compile web page frontend
    uses: ./.github/workflows/web.yml
  check-server-compilation:
    if: "!contains(github.event.head_commit.message, '[skip CI]')"
    name: Compile go server
    uses: ./.github/workflows/server.yml


#  check-mobile-compilation:
#    if: "!contains(github.event.head_commit.message, '[skip CI]')"
#    name: Compile mobile page frontend
#    uses: ./.github/workflows/mobile.yml

  push_to_mirror:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip CI]')
    runs-on: ubuntu-latest
    needs: [check-web-compilation, check-server-compilation]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.REPO_EPITECH_MIRROR }}
          ssh_private_key: ${{ secrets.SSH_KEY }}

  mirror_without_needs:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && contains(github.event.head_commit.message, '[skip CI]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.REPO_EPITECH_MIRROR }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
