name: Check-Server-Compilation

on: [workflow_call]

jobs:
  check-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download
        working-directory: ./server

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install Protogen Go
        run: |
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export GO_PATH=~/go
          export PATH=$PATH:/$GO_PATH/bin
        working-directory: ./server

      - name: Generate protogen files
        run: |
          protoc --go_out=./protogen \
          --go_opt=paths=source_relative \
          --go-grpc_out=./protogen \
          --go-grpc_opt=paths=source_relative gRPC/proto/*.proto
        working-directory: ./server

      - name: Build project
        run: go build -v
        working-directory: ./server
