name: Check-Server-Compilation

on: [push]

jobs:
  check-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download
        working-directory: ./server

      - name: Build project
        run: go build -v
        working-directory: ./server
