name: Check-Web-Compilation

on: [workflow_call]

jobs:
  check-compilation:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: check web compilation
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
